version: '2' # 这个version是指dockerfile解析时用的版本,不是给我们自己定义版本号用的. 
networks: # docker网络设置 
  mysql: # 自定义网络名称 
    driver: bridge # 桥接 
    ipam: # 要使用静态ip必须使用ipam插件 
      driver: default 
      config: 
        - subnet: 172.18.0.0/24 
          gateway: 172.18.0.1
services: 
  m1: # master 
    build: ./mysql/docker/m1 # ./master文件下需要有Dockerfile文件,并且build属性和image属性不能一起使用 
    container_name: m1 # 容器名 
    volumes: # 挂载 下边每行前边的`-`代表这个东西是数组的一个元素.就是说volumes属性的值是一个数组 
      - /home/composer/mysql/config/m1:/etc/mysql/:ro # 注意改下映射关系 
      - /etc/localtime:/etc/localtime:ro 
      - /home/composer/mysql/config/hosts:/etc/hosts:ro # 注意改下映射关系 
      - /home/composer/mysql/data/m1:/var/lib/mysql 
      - /home/composer/mysql/logs/m1:/var/log/mysql 
    networks: # 网络 
      mysql: # 见跟services平级的networks,在最下边 
        ipv4_address: 172.18.0.2 # 设置静态ipv4的地址 
    ulimits: # 操作系统限制 
      nproc: 65535 
    hostname: m1 # hostname 
    mem_limit: 1024m # 最大内存使用不超过1024m,我在本地机器上测试,才只写了1024m,生产上需要根据自己的服务器配置,以及docker容器数进行调优. 
    restart: always # 容器重启策略 
    environment: # 设置环境变量 
      MYSQL_ROOT_PASSWORD: 12345
  s1: # slave1 
    build: ./mysql/docker/s1 
    container_name: s1 
    volumes: 
      - /home/composer/mysql/config/s1/:/etc/mysql/:ro 
      - /etc/localtime:/etc/localtime:ro 
      - /home/composer/mysql/config/hosts:/etc/hosts:ro 
      - /home/composer/mysql/data/s1/:/var/lib/mysql 
      - /home/composer/mysql/logs/s1/:/var/log/mysql 
    networks: 
      mysql: 
        ipv4_address: 172.18.0.3 
    links:
      - m1
    ulimits: 
      nproc: 65535 
    hostname: s1 
    mem_limit: 1024m 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: 12345

